[build]
  publish = "projects/client/dist"
  command = "client:build"
  functions = "projects/server/dist"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  # Rewrite instead of redirect, see https://docs.netlify.com/routing/redirects/rewrites-proxies
  # We're doing this because 301s don't work for HTTP methods other than `GET` or `POST`
  status = 200

[dev]
  autoLaunch = false
